### ISSUE TITLE
Konsolidere spacingskala

### ISSUE THREAD

**Issue by onordbo** [fremtind/jokul#2382]
### Discussed in https://github.com/fremtind/jokul/discussions/2375

<div type='discussions-op-text'>

<sup>Originally posted by **onordbo** October 12, 2021</sup>
Etter litt debatt på Forum rundt bruken og dokumentasjonen av spacingverdiene våre, ble vi enige om at det ikke var noe særlig nytteverdi for oss å skille mellom komponent- og layoutverdier. Per i dag bruker vi t-skjorte størrelser _(xxs, xs, s, m, osv osv)_. Slik jeg har forstått det på den faktiske implementasjonen i Jøkul så varierer dette mellom forkortelser av størrelsen og hele ordet. Såvidt jeg husker så hadde @Saegrov noen meninger om hvordan vi burde navngi selve klassene? Fint om vi deler litt innsikt og eventuelle andre meninger her. Jeg kan fyre opp et issue og ta meg av Figma-dokumentasjonen når vi er i boks.</div>

Vi slår nå sammen spacing og går vekk fra to forskjellige kategorier.

## To-do's
- [x] Definere navngivning for skalaen
- [x] Oppdatere Figma med de nye verdiene og klassenavnene
- [ ] Oppdatere koden og portalen med nye verdier (Under arbeid, #2381.)

**Comment by onordbo** [comment]
Jøkul Bibliotek 2.0 [oppdatert](https://www.figma.com/file/33SNqmJ5ztn7I1algUWdtZ/konsolidere-spacing?node-id=576%3A5686) med ny skala.

cc @Murstam
