### ISSUE TITLE
docs: Faner/Tabs

### ISSUE THREAD

**Issue by onordbo** [fremtind/jokul#2513]
## 📣 Som diskutert og utredet her, trenger vi oppdaterte tabs: https://github.com/fremtind/jokul/discussions/2342
Denne saken omhandler i hovedsak å oppdatere Figma-biblioteket, ettersom selve komponenten allerde er lansert i selve designsystemet via #2441.

## 🎯 To-do's
- [x] Lansere komponenten i portalen
- [x] Dokumentere relevant informasjon om bruk
- [x] Designe inn tabs som komponent i Figma-biblioteket
- [x] Legge inn eksempler på riktig og feil bruk (ref: #2500)
- [x] Sørge for støtte med Variants der det er behov

**Comment by onordbo** [comment]
Tabs med variants er tilgjengelig i biblioteket her: [https://www.figma.com/file/y9JtTf3whfTCHCdYSUXVQ5/J%C3%B8kul-bibliotek-2.0?node-id=2726%3A5453](https://www.figma.com/file/y9JtTf3whfTCHCdYSUXVQ5/J%C3%B8kul-bibliotek-2.0?node-id=2726%3A5453)

Eksempler på riktig og feil bruk er tilgjengelig i [portalen](https://jokul.fremtind.no/komponenter/tabs).
