### ISSUE TITLE
Oppdatere issue templates

### ISSUE THREAD

**Issue by onordbo** [fremtind/jokul#3054]
Dagens varianter er en smule omstendelige og avskrekkende. Vi ser på en forenkling av sjekklister og utvider "ferdige oppsett". Målet burde være at man må skal kunne bruke minst mulig tid på å dele oppgaver og utfordringer med hverandre, med mest mulig automatikk for å gi alle oversikt.

## To-do's
- [ ] Sørg for at alle templates automatisk ligger under Jøkul prosjektboardet
- [ ] Skriv om eksisterende maler til å ha minst mulig tekst og er mest mulig ferdigutfylt
- [ ] Finn ut av hvor mange issue maler vi trenger for å gjøre det enkelt å dele

**Comment by wkillerud** [comment]
Fikser det første punktet i #3055

**Comment by wkillerud** [comment]
Kanskje vi trenger noen av disse?

- Feil i Figma
- Feil i kode
- Feil i portalen
- Endring i Figma
- Endring i kode
- Endring i portalen
- Eksempel på bruk
- Ny komponent

Avhengig av hvor dypt vi vil dykke i denne omgangen så kan Figma/kode/portal kanskje være et valg som en [del av et skjema](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)?

**Comment by onordbo** [comment]
@wkillerud: kan ser for meg at det kan se veldig "mye" ut å ha en hel liste med egne templates for hver type feil og endring, men et skjema slik som du lenker til hadde nice å utforske. Har et forslag i #3056, vi kan bruke det som utgangspunkt og utvide det eventuelt?
