### ISSUE TITLE
Totalrenovering: Ikoner i design og kode

### ISSUE THREAD

**Issue by onordbo** [fremtind/jokul#3066]
Ikonene våre har ligget brakk for lenge både i design og kode. Kodemessig er det implementert diverse “hjemmemekk” og snarveier litt avhengig av hvilken komponent man ser på, mens i Figma har ikonene varierende grad av pikselperfeksjon, størrelser, tykkelser og containere. I portalen er det heller ikke noe særlig dokumentasjon som forklarer hvordan vi forholder oss til ikoner rent praktisk i designsystemhverdagen, utover [prinsippene fra profilen](https://jokul.fremtind.no/profil/ikoner).

I tillegg kan vi bruke denne muligheten til å fange opp eventuelle snøfnugg og få dem lagt inn i designsystemet på en håndterlig måte _(hint hint ikoner i [dekningsvelgeren](https://jokul.fremtind.no/komponenter/list))._

## 🎯 To-do’s

- [ ] Ta en runde på klassifisering av ikontyper ("vanlige" vs handlinger), siden vi har en del udokumenterte ikoner som kun er i bruk og tiltenkt interne løsninger _(f.eks Flyt)_
- [ ] Finn en glætt måte å eksportere ferdige, pikselperfekte ikoner fra Figma til kodebasen “automagisk” 💫
- [x] Gjør et mega-sweep for ikonbruk i koden og erstatt eventuelle outliers med vår ferske, kvadratiske komponent
- [x] Vurder om vi skal bygge inn muligheten for label rett i ikonet, for tilfeller hvor ikonet er klikkbart eller brukes frittstående for en handling/status _(f.eks: åpne/lukke meny)_.
- [x] Gjør det enklere å bruke ikoner både frittstående i komponenter og sammen med tekst _via auto-layout_
- [x] Fjern alt av gamle ikoner fra kodebasen som ikke skal brukes (eller som er utdaterte)
- [x] Sørg for at ikonkomponenten i kode får en kvadratisk container på samme måte som i Figma, så plasseringer blir enklere å forholde seg til
- [x] Lag en ikon-mal og medfølgende dokumentasjon, så det blir enkelt å forstå hvordan ikonene er satt sammen og kan/skal brukes rent Figma-praktisk
- [x] Etabler felles kvadratisk grid (1:1) som alle ikoner skal plasseres på
- [x] Se over ikonstørrelsene våre (i dag har vi small (12x12, 16 bounding), medium (16x16, 24 bounding) og large (20x20, 32 bounding)
- [x] Få alle ikoner inn i sin egen Frame container med alle verdier nullstilt (rotasjon, flip, etc)
- [x] Gå over hele ikonsettet og sørge for at ingen ikoner har halve pikselverdier
- [x] Rentegn eventuelle ikoner som ikke ser ut som de skal
- [x] Sørg for at alle “ferdige” ikoner er flatet ut og ikke har live-strokes som kan skape pikseltrøbbel

## 🔍 Beslektede issues

- [ ] #2779 
- [ ] #3019

**Tanker? Ideer? Andre ting som mangler? Kommenter nedenfor.**

**Comment by wkillerud** [comment]
> Sørg for at ikonkomponenten i kode får en kvadratisk container på samme måte som i Figma, så plasseringer blir enklere å forholde seg til

❤️ 

Savnet senest i dag.

**Comment by onordbo** [comment]
Godt nyttår! Før jul viste vi frem en tidlig versjon av den [nye ikonpakken](https://www.figma.com/file/DektfpgSnhwTVyrcXKwdem/branch/AlEF8t5tMi7mCGzLeKQvw4/Assets?node-id=926%3A9&t=K0YFVJJQgxANFIOp-11). Om det ikke er noen store innvendinger knyttet til oppsettet, vil vi snarlig merge og publisere i Figma for videre testing.

cc @fremtind/design

**Comment by onordbo** [comment]
Statusoppdatering på denne:

- Vi har publisert det nye ikonsettet i Figma så det kan testes
- Vi sjekker ut hvordan det nye settet fungerer i eksisterende komponenter

**Comment by onordbo** [comment]
Lukkbar `Tag` blir visuelt påvirket av det nye kryss ikonet.



![Image](https://user-images.githubusercontent.com/4263132/213434756-40b461c8-67ee-4765-bb33-79912c9660ec.png)(https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/lKfuTFDOn5qU3vSobMrEvE/Components?node-id=5721%3A4678&t=GK2YLffLk7rWZJmk-11)

**Comment by onordbo** [comment]
Disse komponentene får nye ikoner 👇 (cc @fremtind/design)

- [x] [Accordion](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/ijVRpKmaHbp06Kr21fyDaS/Components)
- [x] [Breadcrumb](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/E51QgfOwSpsWPXgMD2m3jw/Components)
- [x] [Checkbox](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/BWXq0305eHT6pYLrm4m2cW/Components) (`assets/icons/check-sm-bold` må tegnes noe tykkere)
- [x] [Expand Button](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/fSgP1tgg6sCx4DBwwG9w3u/Components)
- [x] [Message Box](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/KRsWbdkO8X6vKZ6yYV9QwT/Components) (Har nok fått _litt vel stram_ spacing, tar gjerne mot innspill)
- [x] [Tag](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/lKfuTFDOn5qU3vSobMrEvE/Components)
- [x] [Link](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/urqHgdsT72lKqr677YlGYK/Components)
- [ ] [Text Input](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/iknwXJ0H1SeT90z252qIxF/Components) (Trenger noe mer arbeid)
- [ ] [Button](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/branch/cJLn13oA9MPWP45Tsy7Nyv/Components) (Må jobbes mer med for å løse spacing på en fleksibel måte)
- [ ] Group Title (Ikon mangler i `assets/icons`)

**Comment by onordbo** [comment]
Første runde med ikoner er nå [publisert i Figma](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/Components?version-id=3020495229&node-id=2%3A24&viewport=-189%2C188%2C0.88&t=8XHtfwiEixaFDJjw-0) 🚀

**Comment by onordbo** [comment]
[Tooltip](https://www.figma.com/file/g1CUsWzbCKvDP4AXxyV8zm/Components?version-id=3065578901&node-id=4%3A1709&viewport=25%2C150%2C1.46&t=wA9vE4hlbTagEk1n-0) oppdatert, merget og publisert ✅

**Comment by onordbo** [comment]
Lukker denne på bakgrunn av det arbeidet som allerede er gjort. Oppretter individuelle saker på det som gjenstår på Button og Text Input.
